import { Hackathon } from './types';

// Generate dynamic dates relative to today so deadlines are always relevant and active
const now = new Date();
const addDays = (days: number): string => {
  const d = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);
  return d.toISOString();
};

export const MOCK_HACKATHONS: Hackathon[] = [
  {
    id: '1a2b3c4d-0001-4000-8000-000000000001',
    slug: 'gemini-ai-global-student-sprint',
    title: 'Gemini AI Global Student Sprint 2026',
    description: 'Build breakthrough generative AI agents and multimodal applications solving real-world student challenges using Google Gemini 2.5 and Antigravity APIs.',
    url: 'https://devpost.com/hackathons/gemini-ai-sprint',
    banner_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 50000,
    currency: 'USD',
    location_type: 'Online',
    location_name: 'Worldwide Virtual',
    start_date: addDays(-5),
    submission_deadline: addDays(2), // 2 days left (Critical deadline!)
    tags: ['AI', 'Machine Learning', 'API', 'Open Source', 'Beginner-Friendly'],
    source: 'Devpost',
    is_featured: true,
    is_active: true,
    created_at: addDays(-7),
  },
  {
    id: '1a2b3c4d-0002-4000-8000-000000000002',
    slug: 'hackmit-2026-spring',
    title: 'HackMIT: Genesis 2026',
    description: 'MIT\'s premier collegiate hackathon bringing together over 1,500 students worldwide to hack across hardware, quantum computing, and bio-tech tracks.',
    url: 'https://hackmit.org',
    banner_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 35000,
    currency: 'USD',
    location_type: 'Hybrid',
    location_name: 'Cambridge, MA & Virtual',
    start_date: addDays(1),
    submission_deadline: addDays(4), // 4 days left
    tags: ['Hardware', 'AI', 'Quantum', 'Student Only', 'Web3'],
    source: 'MLH',
    is_featured: true,
    is_active: true,
    created_at: addDays(-10),
  },
  {
    id: '1a2b3c4d-0003-4000-8000-000000000003',
    slug: 'ethglobal-berlin-hackathon',
    title: 'ETHGlobal NextGen Hack 2026',
    description: 'The world\'s biggest decentralized application hackathon. Build layer-2 rollups, zero-knowledge proofs, and automated smart account workflows.',
    url: 'https://ethglobal.com',
    banner_url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 125000,
    currency: 'USD',
    location_type: 'Online',
    location_name: 'Global Discord',
    start_date: addDays(3),
    submission_deadline: addDays(7), // 7 days left (7-day alert window!)
    tags: ['Web3', 'Blockchain', 'Solidity', 'Zero Knowledge', 'FinTech'],
    source: 'Devpost',
    is_featured: false,
    is_active: true,
    created_at: addDays(-14),
  },
  {
    id: '1a2b3c4d-0004-4000-8000-000000000004',
    slug: 'unstop-smart-india-campus-challenge',
    title: 'National Campus Innovation Challenge 2026',
    description: 'Design digital public infrastructure and mobile accessibility solutions for tier-2 and tier-3 colleges. Supported by leading tech firms.',
    url: 'https://unstop.com/hackathons/campus-innovation-2026',
    banner_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 20000,
    currency: 'USD',
    location_type: 'In-Person',
    location_name: 'Bengaluru, India',
    start_date: addDays(5),
    submission_deadline: addDays(12),
    tags: ['Mobile', 'Public Goods', 'Beginner-Friendly', 'FinTech'],
    source: 'Unstop',
    is_featured: false,
    is_active: true,
    created_at: addDays(-4),
  },
  {
    id: '1a2b3c4d-0005-4000-8000-000000000005',
    slug: 'calhacks-climate-tech-fellowship',
    title: 'CalHacks: Green Horizon Hack 2026',
    description: 'UC Berkeley\'s climate-focused hackathon tackling carbon capture tracking, renewable energy grid optimization, and disaster mitigation tech.',
    url: 'https://calhacks.io',
    banner_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 40000,
    currency: 'USD',
    location_type: 'Hybrid',
    location_name: 'Berkeley, CA & Online',
    start_date: addDays(7),
    submission_deadline: addDays(18),
    tags: ['ClimateTech', 'IoT', 'Data Science', 'AI', 'Open Source'],
    source: 'MLH',
    is_featured: true,
    is_active: true,
    created_at: addDays(-2),
  },
  {
    id: '1a2b3c4d-0006-4000-8000-000000000006',
    slug: 'health-hack-stanford-2026',
    title: 'Stanford HealthTech Innovators Cup',
    description: 'Collaborate with medical students and engineers to create clinical decision tools, privacy-preserving patient records, and wearable analytics.',
    url: 'https://med.stanford.edu/health-hackathon',
    banner_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 60000,
    currency: 'USD',
    location_type: 'In-Person',
    location_name: 'Stanford, CA',
    start_date: addDays(10),
    submission_deadline: addDays(24),
    tags: ['Healthcare', 'Biotech', 'Mobile', 'AI'],
    source: 'Devpost',
    is_featured: false,
    is_active: true,
    created_at: addDays(-1),
  },
  {
    id: '1a2b3c4d-0007-4000-8000-000000000007',
    slug: 'solana-summer-camp-students',
    title: 'Solana Student Buildathon 2026',
    description: 'Speed, low fees, high throughput. Build consumer crypto apps, decentralized gaming mechanics, or micro-tipping systems for campus creators.',
    url: 'https://solana.com/hackathons',
    banner_url: 'https://images.unsplash.com/photo-1634704784915-aacf363b021f?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 80000,
    currency: 'USD',
    location_type: 'Online',
    location_name: 'Global',
    start_date: addDays(14),
    submission_deadline: addDays(30),
    tags: ['Web3', 'Rust', 'Gaming', 'FinTech'],
    source: 'Devfolio',
    is_featured: false,
    is_active: true,
    created_at: addDays(-3),
  },
  {
    id: '1a2b3c4d-0008-4000-8000-000000000008',
    slug: 'cybersecurity-capture-the-flag-2026',
    title: 'Global CyberDefense Hack & CTF',
    description: 'Sharpen your defensive security and reverse engineering skills with defensive AI sandboxes, zero-day threat analysis, and automated patching.',
    url: 'https://devpost.com/hackathons/cyberdefense-2026',
    banner_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 30000,
    currency: 'USD',
    location_type: 'Online',
    location_name: 'Worldwide',
    start_date: addDays(8),
    submission_deadline: addDays(21),
    tags: ['Cybersecurity', 'Linux', 'Python', 'Open Source'],
    source: 'Devpost',
    is_featured: false,
    is_active: true,
    created_at: addDays(-5),
  }
];

export const POPULAR_TAGS = [
  'All',
  'AI',
  'Web3',
  'Beginner-Friendly',
  'Open Source',
  'Mobile',
  'ClimateTech',
  'Healthcare',
  'FinTech',
  'Hardware',
  'Cybersecurity'
];
