import { Hackathon } from './types';

// Generate dynamic dates relative to today so deadlines are always relevant and active
const now = new Date();
const addDays = (days: number): string => {
  const d = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);
  return d.toISOString();
};

export const MOCK_HACKATHONS: Hackathon[] = [
  {
    id: '1a2b3c4d-0001-4000-8000-000000000001',
    slug: 'gemini-ai-global-student-sprint',
    title: 'Gemini AI Global Student Sprint 2026',
    description: 'Build breakthrough generative AI agents and multimodal applications solving real-world student challenges using Google Gemini 2.5 and Antigravity APIs.',
    url: 'https://devpost.com/hackathons/gemini-ai-sprint',
    banner_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 50000,
    prize_amount: 50000,
    currency: 'USD',
    prize_currency: 'USD',
    mode: 'online',
    location_type: 'Online',
    location: 'Online (Worldwide)',
    location_name: 'Worldwide Virtual',
    country: 'Global',
    city: 'Online',
    start_date: addDays(-5),
    submission_deadline: addDays(1.5), // < 48 hours left (Critical deadline!)
    registration_end: addDays(1.5),
    tags: ['AI', 'Machine Learning', 'API', 'Open Source', 'Beginner-Friendly'],
    source: 'Devpost',
    is_featured: true,
    is_active: true,
    created_at: addDays(-7),
  },
  {
    id: '1a2b3c4d-0002-4000-8000-000000000002',
    slug: 'flipkart-grid-7-robotics-ai-bangalore',
    title: 'Flipkart GRiD 7.0 Tech Challenge (Bangalore)',
    description: 'India\'s largest flagship engineering challenge. Build autonomous robotics, smart fulfillment algorithms, and high-concurrency e-commerce systems in Bangalore.',
    url: 'https://unstop.com/hackathons/flipkart-grid-7',
    banner_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 1000000,
    prize_amount: 1000000,
    currency: 'INR',
    prize_currency: 'INR',
    mode: 'in-person',
    location_type: 'In-Person',
    location: 'Bangalore, Karnataka, India',
    location_name: 'Flipkart Campus, Bellandur, Bangalore',
    country: 'India',
    state: 'Karnataka',
    city: 'Bangalore',
    start_date: addDays(2),
    submission_deadline: addDays(1.8), // < 48 hours left!
    registration_end: addDays(1.8),
    tags: ['AI', 'Mobile', 'Robotics', 'FinTech', 'Student-Friendly'],
    source: 'Unstop',
    is_featured: true,
    is_active: true,
    created_at: addDays(-5),
  },
  {
    id: '1a2b3c4d-0003-4000-8000-000000000003',
    slug: 'ethindia-2026-bangalore',
    title: 'ETHIndia 2026: Asia\'s Flagship Web3 Buildathon',
    description: 'Asia\'s biggest Web3 gathering in Bangalore. Hack alongside 2,000+ builders on smart contracts, zero-knowledge proofs, and decentralized applications.',
    url: 'https://ethindia.co',
    banner_url: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 2500000,
    prize_amount: 2500000,
    currency: 'INR',
    prize_currency: 'INR',
    mode: 'in-person',
    location_type: 'In-Person',
    location: 'Bangalore, India',
    location_name: 'KTPO Whitefield, Bangalore',
    country: 'India',
    state: 'Karnataka',
    city: 'Bangalore',
    start_date: addDays(4),
    submission_deadline: addDays(3),
    registration_end: addDays(3),
    tags: ['Web3', 'Blockchain', 'Solidity', 'Zero Knowledge', 'FinTech'],
    source: 'Devfolio',
    is_featured: true,
    is_active: true,
    created_at: addDays(-12),
  },
  {
    id: '1a2b3c4d-0004-4000-8000-000000000004',
    slug: 'unstop-smart-india-campus-challenge',
    title: 'National Campus Innovation Challenge 2026',
    description: 'Design digital public infrastructure and mobile accessibility solutions for tier-2 and tier-3 colleges. Grand finale at Bengaluru Tech Summit.',
    url: 'https://unstop.com/hackathons/campus-innovation-2026',
    banner_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 500000,
    prize_amount: 500000,
    currency: 'INR',
    prize_currency: 'INR',
    mode: 'in-person',
    location_type: 'In-Person',
    location: 'Bangalore, India',
    location_name: 'Bengaluru Palace Grounds, Bangalore',
    country: 'India',
    state: 'Karnataka',
    city: 'Bangalore',
    start_date: addDays(5),
    submission_deadline: addDays(12),
    registration_end: addDays(12),
    tags: ['Mobile', 'Open Source', 'Beginner-Friendly', 'FinTech'],
    source: 'Unstop',
    is_featured: false,
    is_active: true,
    created_at: addDays(-4),
  },
  {
    id: '1a2b3c4d-0005-4000-8000-000000000005',
    slug: 'delhi-ai-builders-conclave-2026',
    title: 'Delhi AI Builders Conclave & Hack',
    description: 'North India\'s premier collegiate AI competition. Develop LLM agents, vernacular language models, and civic tech solutions at IIT Delhi.',
    url: 'https://unstop.com/hackathons/delhi-ai-conclave',
    banner_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 300000,
    prize_amount: 300000,
    currency: 'INR',
    prize_currency: 'INR',
    mode: 'in-person',
    location_type: 'In-Person',
    location: 'Delhi, India',
    location_name: 'IIT Delhi, Hauz Khas, Delhi',
    country: 'India',
    state: 'Delhi',
    city: 'Delhi',
    start_date: addDays(6),
    submission_deadline: addDays(10),
    registration_end: addDays(10),
    tags: ['AI', 'Machine Learning', 'Public Goods', 'Python'],
    source: 'Unstop',
    is_featured: false,
    is_active: true,
    created_at: addDays(-6),
  },
  {
    id: '1a2b3c4d-0006-4000-8000-000000000006',
    slug: 'hackmit-2026-spring',
    title: 'HackMIT: Genesis 2026',
    description: 'MIT\'s premier collegiate hackathon bringing together over 1,500 students worldwide to hack across hardware, quantum computing, and bio-tech tracks.',
    url: 'https://hackmit.org',
    banner_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 35000,
    prize_amount: 35000,
    currency: 'USD',
    prize_currency: 'USD',
    mode: 'in-person',
    location_type: 'In-Person',
    location: 'Cambridge, MA, USA',
    location_name: 'MIT Campus, Cambridge, MA',
    country: 'USA',
    state: 'MA',
    city: 'Cambridge',
    start_date: addDays(1),
    submission_deadline: addDays(4),
    registration_end: addDays(4),
    tags: ['Hardware', 'AI', 'Quantum', 'Student Only', 'Web3'],
    source: 'MLH',
    is_featured: true,
    is_active: true,
    created_at: addDays(-10),
  },
  {
    id: '1a2b3c4d-0007-4000-8000-000000000007',
    slug: 'calhacks-climate-tech-fellowship',
    title: 'CalHacks: Green Horizon Hack 2026',
    description: 'UC Berkeley\'s climate-focused hackathon tackling carbon capture tracking, renewable energy grid optimization, and disaster mitigation tech.',
    url: 'https://calhacks.io',
    banner_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 40000,
    prize_amount: 40000,
    currency: 'USD',
    prize_currency: 'USD',
    mode: 'hybrid',
    location_type: 'Hybrid',
    location: 'San Francisco, CA, USA & Online',
    location_name: 'San Francisco & Online',
    country: 'USA',
    state: 'CA',
    city: 'San Francisco',
    start_date: addDays(7),
    submission_deadline: addDays(18),
    registration_end: addDays(18),
    tags: ['ClimateTech', 'IoT', 'Data Science', 'AI', 'Open Source'],
    source: 'MLH',
    is_featured: true,
    is_active: true,
    created_at: addDays(-2),
  },
  {
    id: '1a2b3c4d-0008-4000-8000-000000000008',
    slug: 'solana-summer-camp-students',
    title: 'Solana Student Buildathon 2026',
    description: 'Speed, low fees, high throughput. Build consumer crypto apps, decentralized gaming mechanics, or micro-tipping systems for campus creators.',
    url: 'https://solana.com/hackathons',
    banner_url: 'https://images.unsplash.com/photo-1634704784915-aacf363b021f?auto=format&fit=crop&w=1200&q=80',
    prize_pool: 80000,
    prize_amount: 80000,
    currency: 'USD',
    prize_currency: 'USD',
    mode: 'online',
    location_type: 'Online',
    location: 'Online (Worldwide)',
    location_name: 'Global Discord',
    country: 'Global',
    city: 'Online',
    start_date: addDays(14),
    submission_deadline: addDays(30),
    registration_end: addDays(30),
    tags: ['Web3', 'Rust', 'Gaming', 'FinTech'],
    source: 'Devfolio',
    is_featured: false,
    is_active: true,
    created_at: addDays(-3),
  }
];

export const POPULAR_TAGS = [
  'All',
  'AI',
  'Web3',
  'Beginner-Friendly',
  'Open Source',
  'Mobile',
  'ClimateTech',
  'Healthcare',
  'FinTech',
  'Hardware',
  'Cybersecurity'
];

export const POPULAR_COUNTRIES = [
  { value: 'All', label: 'All Countries' },
  { value: 'India', label: 'India 🇮🇳' },
  { value: 'USA', label: 'USA 🇺🇸' },
  { value: 'Global', label: 'Online / Global 🌐' }
];

export const MAJOR_CITIES_BY_COUNTRY: Record<string, string[]> = {
  India: ['Bangalore', 'Delhi', 'Mumbai', 'Hyderabad', 'Pune', 'Chennai'],
  USA: ['San Francisco', 'New York', 'Cambridge', 'Seattle', 'Austin'],
  All: ['Bangalore', 'Delhi', 'Mumbai', 'Hyderabad', 'San Francisco', 'New York', 'Cambridge']
};
